"""add password version fields

Revision ID: 13f616b24f8f
Revises: 25c764e7e84b
Create Date: 2025-08-20 14:27:01.842494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f616b24f8f'
down_revision = '25c764e7e84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_password_history_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_password_history')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_password_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_password_history_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_password_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('password_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_updated_at')
        batch_op.drop_column('password_version')

    with op.batch_alter_table('user_password_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_password_history_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_password_history_created_at'))

    op.drop_table('user_password_history')
    # ### end Alembic commands ###
