"""add feiyan tables

Revision ID: 18dcce3ae36c
Revises: b6a7d1f0c9e2
Create Date: 2026-01-13 17:37:11.330724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dcce3ae36c'
down_revision = 'b6a7d1f0c9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feiyan_plan_case_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id_ext', sa.String(length=64), nullable=False),
    sa.Column('case_id_ext', sa.String(length=128), nullable=False),
    sa.Column('case_title', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('group_path', sa.String(length=512), nullable=True),
    sa.Column('case_target', sa.Text(), nullable=True),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('workload_minutes', sa.Integer(), nullable=True),
    sa.Column('device_id_ext', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('executed_by_id', sa.String(length=64), nullable=True),
    sa.Column('executed_by_name', sa.String(length=255), nullable=True),
    sa.Column('execution_start_time', sa.String(length=64), nullable=True),
    sa.Column('execution_end_time', sa.String(length=64), nullable=True),
    sa.Column('run_result', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('bug_ref', sa.String(length=128), nullable=True),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feiyan_plan_case_result')),
    sa.UniqueConstraint('case_id_ext', name='uq_feiyan_case_id_ext'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('feiyan_plan_case_result', schema=None) as batch_op:
        batch_op.create_index('ix_feiyan_case_plan', ['plan_id_ext'], unique=False)
        batch_op.create_index(batch_op.f('ix_feiyan_plan_case_result_case_id_ext'), ['case_id_ext'], unique=True)
        batch_op.create_index(batch_op.f('ix_feiyan_plan_case_result_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feiyan_plan_case_result_plan_id_ext'), ['plan_id_ext'], unique=False)
        batch_op.create_index(batch_op.f('ix_feiyan_plan_case_result_updated_at'), ['updated_at'], unique=False)

    op.create_table('feiyan_test_plan',
    sa.Column('plan_id_ext', sa.String(length=64), nullable=False),
    sa.Column('dept_id_ext', sa.String(length=64), nullable=False),
    sa.Column('dept_name', sa.String(length=255), nullable=True),
    sa.Column('project_id_ext', sa.String(length=64), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('plan_start_time', sa.String(length=64), nullable=True),
    sa.Column('plan_end_time', sa.String(length=64), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('blocked', sa.Integer(), nullable=True),
    sa.Column('not_run', sa.Integer(), nullable=True),
    sa.Column('tester_ids', sa.JSON(), nullable=True),
    sa.Column('tester_names', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('plan_id_ext', name=op.f('pk_feiyan_test_plan')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('feiyan_test_plan', schema=None) as batch_op:
        batch_op.create_index('ix_feiyan_plan_dept', ['dept_id_ext'], unique=False)
        batch_op.create_index('ix_feiyan_plan_project', ['project_id_ext'], unique=False)
        batch_op.create_index(batch_op.f('ix_feiyan_test_plan_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feiyan_test_plan_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feiyan_test_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feiyan_test_plan_updated_at'))
        batch_op.drop_index(batch_op.f('ix_feiyan_test_plan_created_at'))
        batch_op.drop_index('ix_feiyan_plan_project')
        batch_op.drop_index('ix_feiyan_plan_dept')

    op.drop_table('feiyan_test_plan')
    with op.batch_alter_table('feiyan_plan_case_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feiyan_plan_case_result_updated_at'))
        batch_op.drop_index(batch_op.f('ix_feiyan_plan_case_result_plan_id_ext'))
        batch_op.drop_index(batch_op.f('ix_feiyan_plan_case_result_created_at'))
        batch_op.drop_index(batch_op.f('ix_feiyan_plan_case_result_case_id_ext'))
        batch_op.drop_index('ix_feiyan_case_plan')

    op.drop_table('feiyan_plan_case_result')
    # ### end Alembic commands ###
