"""init full schema v1

Revision ID: 25c764e7e84b
Revises: 
Create Date: 2025-08-18 16:34:57.505735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c764e7e84b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('code', name=op.f('uq_department_code')),
    sa.UniqueConstraint('name', name=op.f('uq_department_name')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_updated_at'), ['updated_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('fk_attachment_uploaded_by_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_attachment_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_updated_at'), ['updated_at'], unique=False)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], name=op.f('fk_comment_author_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_comment_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_updated_at'), ['updated_at'], unique=False)

    op.create_table('department_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='dept_viewer', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_department_member_department_id_department'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_department_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_member')),
    sa.UniqueConstraint('department_id', 'user_id', name='uq_department_member_department_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('department_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_member_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_member_updated_at'), ['updated_at'], unique=False)

    op.create_table('device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_code', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_device_model_department_id_department'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_model')),
    sa.UniqueConstraint('department_id', 'name', name='uq_device_model_dept_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('device_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_model_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_device_model_dept_active', ['department_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_model_updated_at'), ['updated_at'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_project_department_id_department'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_project_owner_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('code', name=op.f('uq_project_code')),
    sa.UniqueConstraint('department_id', 'name', name='uq_project_dept_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_updated_at'), ['updated_at'], unique=False)

    op.create_table('case_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('order_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['case_group.id'], name=op.f('fk_case_group_parent_id_case_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_case_group_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_group')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('case_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_group_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_case_group_path', ['project_id', 'path'], unique=False)
        batch_op.create_index('ix_case_group_project_parent', ['project_id', 'parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_group_updated_at'), ['updated_at'], unique=False)

    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='tester', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_member_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_project_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_member')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member_project_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_member_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_member_updated_at'), ['updated_at'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_tag_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('project_id', 'name', name='uq_tag_project_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_updated_at'), ['updated_at'], unique=False)

    op.create_table('test_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_test_plan_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_test_plan_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_plan')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('test_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_plan_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_test_plan_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_plan_updated_at'), ['updated_at'], unique=False)

    op.create_table('execution_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('run_type', sa.String(length=32), server_default='manual', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('executed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('passed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('not_run', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plan.id'], name=op.f('fk_execution_run_plan_id_test_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['user.id'], name=op.f('fk_execution_run_triggered_by_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_run')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('execution_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_execution_run_plan_status', ['plan_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_run_updated_at'), ['updated_at'], unique=False)

    op.create_table('plan_device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('device_model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_model.id'], name=op.f('fk_plan_device_model_device_model_id_device_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plan.id'], name=op.f('fk_plan_device_model_plan_id_test_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_device_model')),
    sa.UniqueConstraint('plan_id', 'device_model_id', name='uq_plan_device_model_plan_device'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('plan_device_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_device_model_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_device_model_updated_at'), ['updated_at'], unique=False)

    op.create_table('tag_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_tag_map_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_map')),
    sa.UniqueConstraint('tag_id', 'target_type', 'target_id', name='uq_tag_map_tag_target'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tag_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_map_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_tag_map_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_map_updated_at'), ['updated_at'], unique=False)

    op.create_table('test_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), server_default='P2', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('case_type', sa.String(length=64), server_default='functional', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_test_case_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_test_case_department_id_department'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['case_group.id'], name=op.f('fk_test_case_group_id_case_group'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_test_case_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_test_case_updated_by_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_case')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_case_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_test_case_group', ['group_id'], unique=False)
        batch_op.create_index('ix_test_case_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_case_updated_at'), ['updated_at'], unique=False)

    op.create_table('plan_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_title', sa.String(length=255), nullable=False),
    sa.Column('snapshot_steps', sa.Text(), nullable=True),
    sa.Column('snapshot_expected_result', sa.Text(), nullable=True),
    sa.Column('snapshot_preconditions', sa.Text(), nullable=True),
    sa.Column('snapshot_priority', sa.String(length=16), server_default='P2', nullable=False),
    sa.Column('include', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('order_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('group_path_cache', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['test_case.id'], name=op.f('fk_plan_case_case_id_test_case'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plan.id'], name=op.f('fk_plan_case_plan_id_test_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_case')),
    sa.UniqueConstraint('plan_id', 'case_id', name='uq_plan_case_plan_case'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('plan_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_case_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_plan_case_plan_priority', ['plan_id', 'snapshot_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_case_updated_at'), ['updated_at'], unique=False)

    op.create_table('execution_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('plan_case_id', sa.Integer(), nullable=False),
    sa.Column('device_model_id', sa.Integer(), nullable=True),
    sa.Column('plan_device_model_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('bug_ref', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_model.id'], name=op.f('fk_execution_result_device_model_id_device_model'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_by'], ['user.id'], name=op.f('fk_execution_result_executed_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_case_id'], ['plan_case.id'], name=op.f('fk_execution_result_plan_case_id_plan_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_device_model_id'], ['plan_device_model.id'], name=op.f('fk_execution_result_plan_device_model_id_plan_device_model'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['execution_run.id'], name=op.f('fk_execution_result_run_id_execution_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_result')),
    sa.UniqueConstraint('run_id', 'plan_case_id', 'device_model_id', name='uq_execution_result_run_case_device'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('execution_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_result_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_execution_result_run_status', ['run_id', 'result'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_result_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_result_updated_at'))
        batch_op.drop_index('ix_execution_result_run_status')
        batch_op.drop_index(batch_op.f('ix_execution_result_created_at'))

    op.drop_table('execution_result')
    with op.batch_alter_table('plan_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_case_updated_at'))
        batch_op.drop_index('ix_plan_case_plan_priority')
        batch_op.drop_index(batch_op.f('ix_plan_case_created_at'))

    op.drop_table('plan_case')
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_case_updated_at'))
        batch_op.drop_index('ix_test_case_project_status')
        batch_op.drop_index('ix_test_case_group')
        batch_op.drop_index(batch_op.f('ix_test_case_created_at'))

    op.drop_table('test_case')
    with op.batch_alter_table('tag_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_map_updated_at'))
        batch_op.drop_index('ix_tag_map_target')
        batch_op.drop_index(batch_op.f('ix_tag_map_created_at'))

    op.drop_table('tag_map')
    with op.batch_alter_table('plan_device_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_device_model_updated_at'))
        batch_op.drop_index(batch_op.f('ix_plan_device_model_created_at'))

    op.drop_table('plan_device_model')
    with op.batch_alter_table('execution_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_run_updated_at'))
        batch_op.drop_index('ix_execution_run_plan_status')
        batch_op.drop_index(batch_op.f('ix_execution_run_created_at'))

    op.drop_table('execution_run')
    with op.batch_alter_table('test_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_plan_updated_at'))
        batch_op.drop_index('ix_test_plan_project_status')
        batch_op.drop_index(batch_op.f('ix_test_plan_created_at'))

    op.drop_table('test_plan')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_updated_at'))
        batch_op.drop_index(batch_op.f('ix_tag_created_at'))

    op.drop_table('tag')
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_member_updated_at'))
        batch_op.drop_index(batch_op.f('ix_project_member_created_at'))

    op.drop_table('project_member')
    with op.batch_alter_table('case_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_group_updated_at'))
        batch_op.drop_index('ix_case_group_project_parent')
        batch_op.drop_index('ix_case_group_path')
        batch_op.drop_index(batch_op.f('ix_case_group_created_at'))

    op.drop_table('case_group')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_updated_at'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    op.drop_table('project')
    with op.batch_alter_table('device_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_model_updated_at'))
        batch_op.drop_index('ix_device_model_dept_active')
        batch_op.drop_index(batch_op.f('ix_device_model_created_at'))

    op.drop_table('device_model')
    with op.batch_alter_table('department_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_member_updated_at'))
        batch_op.drop_index(batch_op.f('ix_department_member_created_at'))

    op.drop_table('department_member')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_updated_at'))
        batch_op.drop_index('ix_comment_target')
        batch_op.drop_index(batch_op.f('ix_comment_created_at'))

    op.drop_table('comment')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_updated_at'))
        batch_op.drop_index('ix_attachment_target')
        batch_op.drop_index(batch_op.f('ix_attachment_created_at'))

    op.drop_table('attachment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_updated_at'))
        batch_op.drop_index(batch_op.f('ix_department_created_at'))

    op.drop_table('department')
    # ### end Alembic commands ###
