"""修改部门状态字段为bool 类型，禁用，启用

Revision ID: 673d6868e9ee
Revises: 4dc870a02a7b
Create Date: 2025-08-22 14:30:27.934798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '673d6868e9ee'
down_revision = '4dc870a02a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.drop_column('status')


