"""add dock_nine_grid

Revision ID: c3dbfd53af5a
Revises: 7d2d3f3e4c1b
Create Date: 2025-12-20 13:06:01.637395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dbfd53af5a'
down_revision = '7d2d3f3e4c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dock_nine_gird', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_plan', schema=None) as batch_op:
        batch_op.drop_column('dock_nine_gird')

    # ### end Alembic commands ###
